[project]
name = "coding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.0.1",
    "ipython>=9.6.0",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
]
